### ISSUE TITLE
Not working ;d

### ISSUE THREAD

**Issue by W1tt** [dadus33-plugins/ChatItem#32]
After typing [i] in chat message is changing color to white but it's not showing the item
Plugins:
Plugins (41): ajLeaderboards, ChatInjector, ChatItem, Citizens, CoreProtect, CrackShot, CrazyEnvoy, eGlow, EnderContainers, ePortfel*, Essentials, EssentialsChat, EssentialsSpawn, EZBlocks*, EZPrestige*, EZRanksPro, FastAsyncWorldEdit (WorldEdit), HolographicDisplays, JailMCCore*, JetsPrisonMines, JsonApi*, LibsDisguises, LuckPerms, Multiverse-Core, MythicMobs, NBTAPI, PlaceholderAPI, PlotSquared, ProtocolLib, Scoreboard-revision*, ShopGUIPlus, Shopkeepers, Skellett, Skript, skript-placeholders*, skript-reflect, SuperVanish, TAB, Vault, WorldGuard, WorldGuardExtraFlags
Server version: git-Paper-402 (MC: 1.17.1)
Plugin version: 2.0
PAPI version: 2.11.0

Error:

[00:40:15 ERROR]: [PlaceholderAPI] Unhandled exception occured in onPacketSending(PacketEvent) for PlaceholderAPI
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 46 path $.extra[1].},{
at com.google.gson.internal.Streams.parse(Streams.java:60) ~[patched_1.17.1.jar:git-Paper-402]
at com.google.gson.JsonParser.parseReader(JsonParser.java:85) ~[patched_1.17.1.jar:git-Paper-402]
at com.google.gson.JsonParser.parseReader(JsonParser.java:60) ~[patched_1.17.1.jar:git-Paper-402]
at com.google.gson.JsonParser.parseString(JsonParser.java:47) ~[patched_1.17.1.jar:git-Paper-402]
at com.google.gson.JsonParser.parse(JsonParser.java:98) ~[patched_1.17.1.jar:git-Paper-402]
at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:48) ~[patched_1.17.1.jar:git-Paper-402]
at me.hwn2955.chatinjector.listeners.SpigotChatPacketListener.onPacketSending(SpigotChatPacketListener.java:36) ~[ChatInjector-1.0.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
at net.minecraft.network.Connection.writePacket(Connection.java:423) ~[app:?]
at net.minecraft.network.Connection.send(Connection.java:370) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1997) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1983) ~[app:?]
at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer$1.sendMessage(CraftPlayer.java:2518) ~[patched_1.17.1.jar:git-Paper-402]
at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer$1.sendMessage(CraftPlayer.java:2509) ~[patched_1.17.1.jar:git-Paper-402]
at me.dadus33.chatitem.listeners.ChatListener.lambda$0(ChatListener.java:191) ~[ChatItem-2.0.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
at me.dadus33.chatitem.listeners.ChatListener.onChat(ChatListener.java:161) ~[ChatItem-2.0.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor168.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-402]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-402]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-402]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-402]
at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[patched_1.17.1.jar:git-Paper-402]
at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[patched_1.17.1.jar:git-Paper-402]
at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[patched_1.17.1.jar:git-Paper-402]
at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2179) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2090) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2056) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[app:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 46 path $.extra[1].},{
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[patched_1.17.1.jar:git-Paper-402]
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:529) ~[patched_1.17.1.jar:git-Paper-402]
at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[patched_1.17.1.jar:git-Paper-402]
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:703) ~[patched_1.17.1.jar:git-Paper-402]
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:726) ~[patched_1.17.1.jar:git-Paper-402]
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718) ~[patched_1.17.1.jar:git-Paper-402]
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:726) ~[patched_1.17.1.jar:git-Paper-402]
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:701) ~[patched_1.17.1.jar:git-Paper-402]
at com.google.gson.internal.Streams.parse(Streams.java:48) ~[patched_1.17.1.jar:git-Paper-402]
... 44 more
[00:40:15 ERROR]: Parameters:
net.minecraft.network.protocol.game.PacketPlayOutChat@752d9a[
a=<null>
components={TextComponent{text=, BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=[TextComponent{text=[A], BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text= , BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text=[D], BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text= , BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text=W1tt, BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text= , BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text=», BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text= , BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text=[i], BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text= , BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}], clickEvent=null, hoverEvent=null)}}
b=SYSTEM
c=00000000-0000-0000-0000-000000000000
]

**Comment by W1tt** [comment]
Today i found out that it happens only if you start a message with [i]. When you put sth before it, it works perfectly

**Comment by Elikill58** [comment]
I failed to reproduce with dev build, so I think it have been fixed since this time
